### PR TITLE
Initial tests.

### PR DESCRIPTION
**Pull request by tokejepsen**
This is related to #17

### CODE REVIEW

**Comment by tokejepsen** [comment]
Alright, we are back to the same issue as before; the ```avalon``` executable on linux does not seem to be forwarding on the arguments passed to it.

**Comment by mottosso** [comment]
Ok, not entirely sure testing the CLI through Python is the right approach. Maybe we should try testing the CLI via the command-line instead. Let me try something..

**Comment by mottosso** [comment]
Sorry, I'm totally hijacking this. :P

**Comment by mottosso** [comment]
Done, let me know what you think.

**Comment by tokejepsen** [comment]
> Sorry, I'm totally hijacking this

Its all good. I was lost anyways :)

So we are currently not using nose for any tests, then?

**Comment by mottosso** [comment]
> So we are currently not using nose for any tests, then?

Hah, no. It doesn't look like it. Let's save nose for when we do tests not involving the CLI.

**Comment by mottosso** [comment]
Btw I've added the synchronisation with CGWire, so that should work now.

I haven't figured out a good way of running it yet, at the moment you can start it from `terminal.bat` like so:

```bash
$ python a:\sync.py
```

It'll refresh Avalon with data from CGWire every 10 seconds. So now we can create projects, assets and shots from there, but there isn't any way to manage applications or path templates yet. That's something we should have a chat with Frank about.

**Comment by tokejepsen** [comment]
> Btw I've added the synchronisation with CGWire, so that should work now.

Very cool!

I was thinking the syncing daemon would be part of the docker container?

**Comment by mottosso** [comment]
Let's continue here: https://github.com/getavalon/docker/issues/23

**Pull request merged**
