### PR TITLE
Project Manager

### PR DESCRIPTION
**Pull request by tokejepsen**
**Goal**

Have the Project Manager be the starting point for users.

**Implementation**

Initially this just exposes the manager to the distribution with ```avalon --manager```. Currently the Project Manager does not have features to create/save/load projects, so you have to pass a project name to load ```avalon --manager myProject```.

Once the Project Manager can create/load/save projects, this PR can be merged.

### CODE REVIEW

**Comment by mottosso** [comment]
Good idea!

**Comment by tokejepsen** [comment]
I was going to abandon this development work in favour of CGWire integration development. Although anyone could pick up the work from here.

Another thought I had was whether ```avalon --manager``` should be the entrypoint for all project managers like CGWire/Ftrack/Shotgun?
In the case of online managers this would simply open the webbrowser.

**Comment by tokejepsen** [comment]
Experimenting further with CGWire, and I think the Project Manager still has a productive place to fill in the Avalon pipeline.

There are a number of features/issues that needs looking at in CGWire to be on-par with the Project Manager.

**Comment by mottosso** [comment]
How about implementing those in CGWire? It's open source, and I could put up a guide for how to get started - it took a while to figure out (lots and lots of steps and out of date docs), but I managed to boil it down to 1 clone and 1 docker run, no install.

**Comment by tokejepsen** [comment]
> How about implementing those in CGWire?

Yeah, I would definitely be up for looking at that. And a guide to get started would help a lot!

Still think that this PR has a place to be merged. CGWire is not an easy project to get into, and some studios might prefer not to use it at all.

**Comment by tokejepsen** [comment]
Actually have just tested colorbleeds launcher out, and it has easy access to the project manager, so think we may not need this PR after all.

**Comment by mottosso** [comment]
Ok, let's resubmit if it becomes interesting again.

**Pull request closed without merging**
