### PR TITLE
Documentation about updating.

### PR DESCRIPTION
**Pull request by tokejepsen**
Neither samba or cgwire has any version tags, so would need to update the base image.

### CODE REVIEW

**Comment by mottosso** [comment]
Who's updating? The user or `getavalon/docker` developer?

For the user, they should rely on the version of `avalon/files`, e.g. `:0.4`. For the developer, wouldn't is be rebuilding the image, not using a cache? Does pulling these base images even update `avalon/files` and friends? I would have thought they are separate images altogether.

**Comment by tokejepsen** [comment]
> Who's updating? The user or getavalon/docker developer?

This came from me trying to update cgwire. So I guess its the developer.

> For the user, they should rely on the version of avalon/files, e.g. :0.4. For the developer, wouldn't it be rebuilding the image, not using a cache? Does pulling these base images even update avalon/files and friends? I would have thought they are separate images altogether.

I honestly don't know, hence this PR which is also a discussion about how to handle this. If there is a newer version of cgwire, how do we test this out locally?

**Comment by mottosso** [comment]
> I honestly don't know, hence this PR which is also a discussion about how to handle this.

Yes I think so.

If you `docker build ....` and pass `--no-cache`, then it will build the image anew, pulling the latest base image.

> If there is a newer version of cgwire, how do we test this out locally?

This is the shitty thing; because they aren't versioned, we can't control nor know about it. Best we can do is keep an eye on either Docker Hub or GitHub to see when it's been updated, and then do the above.

If he doesn't version soon, we could copy his Dockerfile and version ourselves; it'd just mean extra build time for our Travis and having to port changes he might be doing ourselves. Not ideal, but we need to have a fixed version.

**Comment by tokejepsen** [comment]
> If you docker build .... and pass --no-cache, then it will build the image anew, pulling the latest base image.

That is probably the missing piece in my knowledge.

**Pull request closed without merging**
